name: Test workflow

on:
  push:
  pull_request: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build Application
        run: echo "hello world!"

  deploy:
    name: Deploy to Production
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Cloud Provider
        run: sleep 120s
